spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # URL подключения к PostgreSQL
    username: postgres_user # Имя пользователя базы данных
    password: postgres_password # Пароль пользователя базы данных
    driver-class-name: org.postgresql.Driver # Класс драйвера для PostgreSQL
    hikari:
      maximum-pool-size: 10 # Максимальное количество соединений в пуле
      minimum-idle: 2 # Минимальное количество соединений, которые остаются открытыми
      idle-timeout: 30000 # Время ожидания соединения в миллисекундах
      max-lifetime: 1800000 # Максимальное время жизни соединения в миллисекундах

  jpa:
    hibernate:
      ddl-auto: update # Автоматическое создание и обновление схемы базы данных
      dialect: org.hibernate.dialect.PostgreSQLDialect # Явное указание диалекта PostgreSQL
    properties:
      hibernate:
        show_sql: true # Включить вывод SQL-запросов в консоль
        format_sql: true # Форматировать SQL-запросы для удобства чтения
        use_sql_comments: true # Добавлять комментарии в SQL-запросы
        jdbc:
          batch_size: 1000 # Размер батча для вставок
        order_inserts: true # Оптимизация порядка вставок
        flush.mode: MANUAL # Ручное управление flush для повышения производительности
