spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/production_db
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
