CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    created_at VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    last_quantity_update VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    sku VARCHAR(255) NOT NULL
