ktor {
    deployment {
        port = 80
    }
    application {
        modules = [ com.example.ApplicationKt.module ]
    }
    database {
        url = ${?DATABASE_CONNECTION_STRING}
        user = ${?POSTGRES_USER}
        password = ${?POSTGRES_PASSWORD}
    }
}
