ktor {
    deployment {
        port = 8080
        port = ${?SERVER_PORT}
    }
    application {
        modules = [ com.example.ApplicationKt.module ]
    }
    database {
        url = "jdbc:postgresql://localhost:5432/artemmovchan"
        user = ${?POSTGRES_USER}
        password = ${?POSTGRES_PASSWORD}
    }
}
